/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': 'var(--color-primary)',
        'primary-container': 'var(--color-primary-container)',
        'primary-dark': 'var(--color-primary-dark)',
        'on-primary': 'var(--color-on-primary)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'secondary': 'var(--color-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'tertiary': 'var(--color-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'error': 'var(--color-error)',
        'error-container': 'var(--color-error-container)',
        'error-red': 'var(--color-error-red)',
        'on-error': 'var(--color-on-error)',
        'on-error-container': 'var(--color-on-error-container)',
        'background': 'var(--color-background)',
        'surface': 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-tint': 'var(--color-surface-tint)',
        'on-background': 'var(--color-on-background)',
        'outline': 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'border-light': 'var(--color-border-light)',
        'text-deep': 'var(--color-text-deep)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'bg-peach-soft': 'var(--color-bg-peach-soft)',
        'bg-peach-mid': 'var(--color-bg-peach-mid)',
        'gold-premium': 'var(--color-gold-premium)',
        'star-yellow': 'var(--color-star-yellow)',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        'xxl': '24px',
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '24px',
      },
      fontFamily: {
        'sans': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'title-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'header-md': ['Plus Jakarta Sans', 'sans-serif'],
        'section-title': ['Plus Jakarta Sans', 'sans-serif'],
        'body-base': ['Plus Jakarta Sans', 'sans-serif'],
        'price-highlight': ['Plus Jakarta Sans', 'sans-serif'],
        'label-bold': ['Plus Jakarta Sans', 'sans-serif'],
        'small-subtext': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['34px', { lineHeight: '40px', fontWeight: '800', letterSpacing: '-1px' }],
        'title-lg': ['28px', { lineHeight: '34px', fontWeight: '800' }],
        'header-md': ['20px', { lineHeight: '26px', fontWeight: '700' }],
        'section-title': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'body-base': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'price-highlight': ['15px', { lineHeight: '22px', fontWeight: '800' }],
        'label-bold': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'small-subtext': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      boxShadow: {
        'card': '0 4px 12px rgba(0,0,0,0.08)',
        'card-hover': '0 8px 24px rgba(0,0,0,0.12)',
        'card-featured': '0 4px 12px rgba(255,107,53,0.15)',
        'button-primary': '0 4px 12px rgba(255,107,53,0.25)',
      },
    },
  },
  plugins: [],
}
