/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#ab3500',
        'primary-container': '#ff6b35',
        'primary-dark': '#E55A2B',
        'on-primary': '#ffffff',
        'on-primary-container': '#5f1900',
        'primary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#ffb59d',
        'on-primary-fixed': '#390c00',
        'on-primary-fixed-variant': '#832600',
        'inverse-primary': '#ffb59d',
        'secondary': '#006a60',
        'secondary-container': '#8cf5e4',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#007166',
        'secondary-fixed': '#8cf5e4',
        'secondary-fixed-dim': '#6fd8c8',
        'on-secondary-fixed': '#00201c',
        'on-secondary-fixed-variant': '#005048',
        'tertiary': '#765a05',
        'tertiary-container': '#b69541',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#3f2f00',
        'tertiary-fixed': '#ffdf96',
        'tertiary-fixed-dim': '#e7c268',
        'on-tertiary-fixed': '#251a00',
        'on-tertiary-fixed-variant': '#5a4400',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'error-red': '#E63946',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'background': '#f8f9fa',
        'surface': '#FFFFFF',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#594139',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#ab3500',
        'on-background': '#191c1d',
        'outline': '#8d7168',
        'outline-variant': '#e1bfb5',
        'border-light': '#E5E7EB',
        'text-deep': '#1A1A2E',
        'text-secondary': '#6B7280',
        'text-muted': '#9CA3AF',
        'bg-peach-soft': '#FFECE0',
        'bg-peach-mid': '#FFE2D0',
        'gold-premium': '#FFD700',
        'star-yellow': '#F59E0B',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        'xxl': '24px',
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '24px',
      },
      fontFamily: {
        'sans': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'title-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'header-md': ['Plus Jakarta Sans', 'sans-serif'],
        'section-title': ['Plus Jakarta Sans', 'sans-serif'],
        'body-base': ['Plus Jakarta Sans', 'sans-serif'],
        'price-highlight': ['Plus Jakarta Sans', 'sans-serif'],
        'label-bold': ['Plus Jakarta Sans', 'sans-serif'],
        'small-subtext': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['34px', { lineHeight: '40px', fontWeight: '800', letterSpacing: '-1px' }],
        'title-lg': ['28px', { lineHeight: '34px', fontWeight: '800' }],
        'header-md': ['20px', { lineHeight: '26px', fontWeight: '700' }],
        'section-title': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'body-base': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'price-highlight': ['15px', { lineHeight: '22px', fontWeight: '800' }],
        'label-bold': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'small-subtext': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      boxShadow: {
        'card': '0 4px 12px rgba(0,0,0,0.08)',
        'card-hover': '0 8px 24px rgba(0,0,0,0.12)',
        'card-featured': '0 4px 12px rgba(255,107,53,0.15)',
        'button-primary': '0 4px 12px rgba(255,107,53,0.25)',
      },
    },
  },
  plugins: [],
}
